[vowels]
"अ" = "ꢂ"
"आ" = "ꢃ"
"इ" = "ꢄ"
"ई" = "ꢅ"
"उ" = "ꢆ"
"ऊ" = "ꢇ"
"ऋ" = "ꢈ"
"ॠ" = "ꢉ"
"ऌ" = "ꢊ"
"ॡ" = "ꢋ"
"ऎ" = "ꢌ"
"ए" = "ꢍ"
"ऐ" = "ꢎ"
"ऒ" = "ꢏ"
"ओ" = "ꢐ"
"औ" = "ꢑ"
"ऍ" = "ꢌ"
"ऑ" = "ꢃ"

[vowel_marks]
"ा" = "ꢵ"
"ि" = "ꢶ"
"ी" = "ꢷ"
"ु" = "ꢸ"
"ू" = "ꢹ"
"ृ" = "ꢺ"
"ॄ" = "ꢻ"
"ॢ" = "ꢼ"
"ॣ" = "ꢽ"
"ॆ" = "ꢾ"
"े" = "ꢿ"
"ै" = "ꣀ"
"ॊ" = "ꣁ"
"ो" = "ꣂ"
"ौ" = "ꣃ"
"ॅ" = "ꢾ"
"ॉ" = "ꢵ"

[yogavaahas]
"ं" = "ꢀ"
"ः" = "ꢁ"
"ँ" = "◌ꣅ"
"ᳵ" = "ᳵ"
"ᳶ" = "ᳶ"
"ꣳ" = "ꣳ"

[virama]
"्" = "◌꣄"

[consonants]
"क" = "ꢒ"
"ख" = "ꢓ"
"ग" = "ꢔ"
"घ" = "ꢕ"
"ङ" = "ꢖ"
"च" = "ꢗ"
"छ" = "ꢘ"
"ज" = "ꢙ"
"झ" = "ꢚ"
"ञ" = "ꢛ"
"ट" = "ꢜ"
"ठ" = "ꢝ"
"ड" = "ꢞ"
"ढ" = "ꢟ"
"ण" = "ꢠ"
"त" = "ꢡ"
"थ" = "ꢢ"
"द" = "ꢣ"
"ध" = "ꢤ"
"न" = "ꢥ"
"प" = "ꢦ"
"फ" = "ꢧ"
"ब" = "ꢨ"
"भ" = "ꢩ"
"म" = "ꢪ"
"य" = "ꢫ"
"र" = "ꢬ"
"ल" = "ꢭ"
"व" = "ꢮ"
"श" = "ꢯ"
"ष" = "ꢰ"
"स" = "ꢱ"
"ह" = "ꢲ"
"ळ" = "ꢳ"
"क्ष" = "ꢒ꣄\u200dꢰ"
"ज्ञ" = "ꢙ꣄ꢛ"

[symbols]
"०" = "꣐"
"१" = "꣑"
"२" = "꣒"
"३" = "꣓"
"४" = "꣔"
"५" = "꣕"
"६" = "꣖"
"७" = "꣗"
"८" = "꣘"
"९" = "꣙"
"ॐ" = "ꢐꢀ"
"ऽ" = "ऽ"
"।" = "꣎"
"॥" = "꣏"

[extra_consonants]
"क़" = "ꢒ"
"ख़" = "ꢓ"
"ग़" = "ꢔ"
"ज़" = "ꢙ"
"ड़" = "ꢞ"
"ढ़" = "ꢟ"
"फ़" = "ꢧ"
"य़" = "ꢫ"
